# Generated by Django 4.0.4 on 2022-05-01 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=128)),
                ('postalCode', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('shippingPrice', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='base.order')),
            ],
        ),
    ]
