# Generated by Django 4.0.4 on 2022-07-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='texPrice',
            new_name='taxPrice',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
